name: Run command
on:
  issues:

jobs:
  run:
    name: "Run command ${{ github.event.issue.title }}"
    runs-on: ubuntu-latest
    steps:
      - name: Validate Request
        id: validate
        env:
          TITLE: "${{ github.event.issue.title }}"
          ACTOR: "${{ github.actor }}"
        run: |
          echo "#######[STEP-1]#######"
          echo "Prepare to run: $TITLE"

          echo "#######[STEP-2]#######"
          echo "Check the actor is allowed to execute command"
          ALLOWED_ACTORS=("tr0l", "krimdaouas-design")

          if [[ " ${ALLOWED_ACTORS[@]} " =~ " $ACTOR " ]]; then
            echo "User is allowed to run script"
          else
            echo "User is NOT allowed to run script"
            echo "skip=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          echo "#######[STEP-3]#######"
          COMMAND="$TITLE"
          if [[ "$COMMAND" == gh\ * ]]; then
            echo "Command is valid"
            echo "valid_command=true" >> $GITHUB_OUTPUT
            echo "command=$COMMAND" >> $GITHUB_OUTPUT
          else
            echo "Command NOT valid"
            echo "skip=true" >> $GITHUB_OUTPUT
            echo "skip_reason=INVALID_COMMAND" >> $GITHUB_OUTPUT
          fi

      - name: Run the command
        if: ${{ steps.validate.outputs.skip != 'true' }}
        env:
          FLAG: "flag{example_flag}"
        run: |
          echo "Running command: ${{ steps.validate.outputs.command }}"
          echo "FLAG: '${{ github.event.issue.title }}'"

      - name: Skipped
        if: ${{ steps.validate.outputs.skip == 'true' }}
        run: |
          echo "Skipped: ${{ steps.validate.outputs.skip_reason }}"
          echo "::error::Something went wrong: ${{ steps.validate.outputs.skip_reason }}"
