name: Run command
on:
  issues:
    types: [opened]

jobs:
  run:
    name: "Run command ${{ github.event.issue.title }}"
    runs-on: ubuntu-latest
    steps:
      - name: Validate Request
        id: validate
        env:
          TITLE: "${{ github.event.issue.title }}"
          ACTOR: "${{ github.actor }}"
          # Ici tu peux mettre un dummy tag, ou extraire depuis le titre
          COMMAND: "echo dummy-tag"
        run: |
         echo "#######[STEP-1]#######"
         echo "Prepare to run: $TITLE"
         echo "command=$TITLE" >> $GITHUB_OUTPUT
         echo "valid-command=true" >> $GITHUB_OUTPUT

      - name: Run the command
        if: ${{ steps.validate.outputs.skip != 'true' }}
        run: |
          echo "Running command..."
          echo "Command: ${{ steps.validate.outputs.command }}"
          ${{ steps.validate.outputs.command }}

      - name: Skipped
        if: ${{ steps.validate.outputs.skip == 'true' }}
        run: |
          echo "Skipped: ${{ steps.validate.outputs.skip-reason }}"
          echo "::error::Something went wrong: ${{ steps.validate.outputs.skip-reason }}"
